import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { routes } from "./routes/routes";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* Menu de navegação */}
        {/* <nav>
          <ul>
            {routes.map((route) => (
              <li key={route.path}>
                <a href={route.path}>{route.path}</a>
              </li>
            ))}
          </ul>
        </nav> */}

        {/* Renderizando o conteúdo da página */}
        <main>{children}</main>
      </body>
    </html>
  );
}
